# Category: Init
# Service: Docker NodeJS Initialization Dockerfile
# Description: Initialization environment for Node.js to bootstrap the application.
# Maintainer: ryumada
FROM node:${DOCKER_NODEJS_TAG}

# Add user and group with matching IDs from the host to fix permissions
ARG HOST_USER_ID
ARG HOST_GROUP_ID
RUN groupmod -g ${HOST_GROUP_ID} node && \
    usermod -u ${HOST_USER_ID} -g ${HOST_GROUP_ID} node

USER node

WORKDIR /usr/src/app

# Hardening: Disable Next.js telemetry
ENV NEXT_TELEMETRY_DISABLED=1

# No COPY commands here because we are initializing an empty project
# The source code will be generated inside the volume mount

# Start the container and keep it running
CMD ["sleep", "infinity"]
