# STAGE 1: Initialization environment for Node.js
# This image is used to bootstrap the application (e.g. create-next-app)
FROM node:${DOCKER_NODEJS_TAG}

# Add user and group with matching IDs from the host to fix permissions
ARG HOST_USER_ID
ARG HOST_GROUP_ID
RUN groupmod -g ${HOST_GROUP_ID} node && \
    usermod -u ${HOST_USER_ID} -g ${HOST_GROUP_ID} node

USER node

WORKDIR /usr/src/app

# No COPY commands here because we are initializing an empty project
# The source code will be generated inside the volume mount

# Start the container and keep it running
CMD ["sleep", "infinity"]
